using LLMSharp.Google.Palm.Common;
using System.Collections.Generic;
using static Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types;

namespace LLMSharp.Google.Palm
{
    /// <summary>
    /// TextCompletions returned by the GenerateText
    /// </summary>
    public class PalmTextCompletion
    {
        /// <summary>
        /// A list of candidate text completions generated by the model.
        /// </summary>
        public IEnumerable<PalmCompletionCandidate>? Candidates { get; set; }

        /// <summary>
        /// The output of the first candidate
        /// </summary>
        public PalmCompletionCandidate? Result { get; set; }

        /// <summary>
        /// Indicates the reasons why content may have been blocked.
        /// </summary>
        public IEnumerable<PalmContentFilter>? Filters { get; set; }

        /// <summary>
        /// Indicates which safety settings blocked content in this result.
        /// </summary>
        public PalmSafetySetting? SafetyFeedback { get; set; }
    }
}
