using LLMSharp.Google.Palm.Common;
using System.Collections.Generic;
using System.Linq;
using gav = Google.Ai.Generativelanguage.V1Beta2;

namespace LLMSharp.Google.Palm
{
    /// <summary>
    /// TextCompletions returned by the GenerateText
    /// </summary>
    public class PalmTextCompletionResponse
    {
        /// <summary>
        /// A list of candidate text completions generated by the model.
        /// </summary>
        public IEnumerable<PalmCompletionCandidate> Candidates { get; private set; } = Enumerable.Empty<PalmCompletionCandidate>();

        /// <summary>
        /// The output of the first candidate
        /// </summary>
        public PalmCompletionCandidate? Result { get; private set; }

        /// <summary>
        /// Indicates the reasons why content may have been blocked.
        /// </summary>
        public IEnumerable<PalmContentFilter> Filters { get; private set; } = Enumerable.Empty<PalmContentFilter>();

        /// <summary>
        /// Indicates which safety settings blocked content in this result.
        /// </summary>
        public IEnumerable<PalmSafetyFeedback> SafetyFeedback { get; private set; } = Enumerable.Empty<PalmSafetyFeedback>();

        internal PalmTextCompletionResponse(gav::GenerateTextResponse response)
        {
            this.SafetyFeedback = response.SafetyFeedback.Select(s => new PalmSafetyFeedback(s));
            this.Filters = response.Filters.Select(f => new PalmContentFilter(f));
            this.Candidates = response.Candidates.Select(c => new PalmCompletionCandidate(c));
            this.Result = this.Candidates.FirstOrDefault();
        }
    }
}
