// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ai/generativelanguage/v1beta2/discuss_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Ai.Generativelanguage.V1Beta2 {

  /// <summary>Holder for reflection information generated from google/ai/generativelanguage/v1beta2/discuss_service.proto</summary>
  public static partial class DiscussServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for google/ai/generativelanguage/v1beta2/discuss_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DiscussServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjpnb29nbGUvYWkvZ2VuZXJhdGl2ZWxhbmd1YWdlL3YxYmV0YTIvZGlzY3Vz",
            "c19zZXJ2aWNlLnByb3RvEiRnb29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdl",
            "LnYxYmV0YTIaM2dvb2dsZS9haS9nZW5lcmF0aXZlbGFuZ3VhZ2UvdjFiZXRh",
            "Mi9jaXRhdGlvbi5wcm90bxoxZ29vZ2xlL2FpL2dlbmVyYXRpdmVsYW5ndWFn",
            "ZS92MWJldGEyL3NhZmV0eS5wcm90bxocZ29vZ2xlL2FwaS9hbm5vdGF0aW9u",
            "cy5wcm90bxoXZ29vZ2xlL2FwaS9jbGllbnQucHJvdG8aH2dvb2dsZS9hcGkv",
            "ZmllbGRfYmVoYXZpb3IucHJvdG8aGWdvb2dsZS9hcGkvcmVzb3VyY2UucHJv",
            "dG8izgIKFkdlbmVyYXRlTWVzc2FnZVJlcXVlc3QSPgoFbW9kZWwYASABKAlC",
            "L+BBAvpBKQonZ2VuZXJhdGl2ZWxhbmd1YWdlLmdvb2dsZWFwaXMuY29tL01v",
            "ZGVsEkgKBnByb21wdBgCIAEoCzIzLmdvb2dsZS5haS5nZW5lcmF0aXZlbGFu",
            "Z3VhZ2UudjFiZXRhMi5NZXNzYWdlUHJvbXB0QgPgQQISHQoLdGVtcGVyYXR1",
            "cmUYAyABKAJCA+BBAUgAiAEBEiEKD2NhbmRpZGF0ZV9jb3VudBgEIAEoBUID",
            "4EEBSAGIAQESFwoFdG9wX3AYBSABKAJCA+BBAUgCiAEBEhcKBXRvcF9rGAYg",
            "ASgFQgPgQQFIA4gBAUIOCgxfdGVtcGVyYXR1cmVCEgoQX2NhbmRpZGF0ZV9j",
            "b3VudEIICgZfdG9wX3BCCAoGX3RvcF9rIuMBChdHZW5lcmF0ZU1lc3NhZ2VS",
            "ZXNwb25zZRJBCgpjYW5kaWRhdGVzGAEgAygLMi0uZ29vZ2xlLmFpLmdlbmVy",
            "YXRpdmVsYW5ndWFnZS52MWJldGEyLk1lc3NhZ2USPwoIbWVzc2FnZXMYAiAD",
            "KAsyLS5nb29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuTWVz",
            "c2FnZRJECgdmaWx0ZXJzGAMgAygLMjMuZ29vZ2xlLmFpLmdlbmVyYXRpdmVs",
            "YW5ndWFnZS52MWJldGEyLkNvbnRlbnRGaWx0ZXIipwEKB01lc3NhZ2USEwoG",
            "YXV0aG9yGAEgASgJQgPgQQESFAoHY29udGVudBgCIAEoCUID4EECElsKEWNp",
            "dGF0aW9uX21ldGFkYXRhGAMgASgLMjYuZ29vZ2xlLmFpLmdlbmVyYXRpdmVs",
            "YW5ndWFnZS52MWJldGEyLkNpdGF0aW9uTWV0YWRhdGFCA+BBA0gAiAEBQhQK",
            "El9jaXRhdGlvbl9tZXRhZGF0YSKxAQoNTWVzc2FnZVByb21wdBIUCgdjb250",
            "ZXh0GAEgASgJQgPgQQESRAoIZXhhbXBsZXMYAiADKAsyLS5nb29nbGUuYWku",
            "Z2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuRXhhbXBsZUID4EEBEkQKCG1l",
            "c3NhZ2VzGAMgAygLMi0uZ29vZ2xlLmFpLmdlbmVyYXRpdmVsYW5ndWFnZS52",
            "MWJldGEyLk1lc3NhZ2VCA+BBAiKGAQoHRXhhbXBsZRI8CgVpbnB1dBgBIAEo",
            "CzItLmdvb2dsZS5haS5nZW5lcmF0aXZlbGFuZ3VhZ2UudjFiZXRhMi5NZXNz",
            "YWdlEj0KBm91dHB1dBgCIAEoCzItLmdvb2dsZS5haS5nZW5lcmF0aXZlbGFu",
            "Z3VhZ2UudjFiZXRhMi5NZXNzYWdlIqUBChlDb3VudE1lc3NhZ2VUb2tlbnNS",
            "ZXF1ZXN0Ej4KBW1vZGVsGAEgASgJQi/gQQL6QSkKJ2dlbmVyYXRpdmVsYW5n",
            "dWFnZS5nb29nbGVhcGlzLmNvbS9Nb2RlbBJICgZwcm9tcHQYAiABKAsyMy5n",
            "b29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuTWVzc2FnZVBy",
            "b21wdEID4EECIjEKGkNvdW50TWVzc2FnZVRva2Vuc1Jlc3BvbnNlEhMKC3Rv",
            "a2VuX2NvdW50GAEgASgFMpYECg5EaXNjdXNzU2VydmljZRL7AQoPR2VuZXJh",
            "dGVNZXNzYWdlEjwuZ29vZ2xlLmFpLmdlbmVyYXRpdmVsYW5ndWFnZS52MWJl",
            "dGEyLkdlbmVyYXRlTWVzc2FnZVJlcXVlc3QaPS5nb29nbGUuYWkuZ2VuZXJh",
            "dGl2ZWxhbmd1YWdlLnYxYmV0YTIuR2VuZXJhdGVNZXNzYWdlUmVzcG9uc2Ui",
            "a4LT5JMCLiIpL3YxYmV0YTIve21vZGVsPW1vZGVscy8qfTpnZW5lcmF0ZU1l",
            "c3NhZ2U6ASraQTRtb2RlbCxwcm9tcHQsdGVtcGVyYXR1cmUsY2FuZGlkYXRl",
            "X2NvdW50LHRvcF9wLHRvcF9rEt8BChJDb3VudE1lc3NhZ2VUb2tlbnMSPy5n",
            "b29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuQ291bnRNZXNz",
            "YWdlVG9rZW5zUmVxdWVzdBpALmdvb2dsZS5haS5nZW5lcmF0aXZlbGFuZ3Vh",
            "Z2UudjFiZXRhMi5Db3VudE1lc3NhZ2VUb2tlbnNSZXNwb25zZSJGgtPkkwIx",
            "IiwvdjFiZXRhMi97bW9kZWw9bW9kZWxzLyp9OmNvdW50TWVzc2FnZVRva2Vu",
            "czoBKtpBDG1vZGVsLHByb21wdBokykEhZ2VuZXJhdGl2ZWxhbmd1YWdlLmdv",
            "b2dsZWFwaXMuY29tQpkBCihjb20uZ29vZ2xlLmFpLmdlbmVyYXRpdmVsYW5n",
            "dWFnZS52MWJldGEyQhNEaXNjdXNzU2VydmljZVByb3RvUAFaVmdvb2dsZS5n",
            "b2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvYWkvZ2VuZXJhdGl2ZWxh",
            "bmd1YWdlL3YxYmV0YTI7Z2VuZXJhdGl2ZWxhbmd1YWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Ai.Generativelanguage.V1Beta2.CitationReflection.Descriptor, global::Google.Ai.Generativelanguage.V1Beta2.SafetyReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Api.ClientReflection.Descriptor, global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest), global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest.Parser, new[]{ "Model", "Prompt", "Temperature", "CandidateCount", "TopP", "TopK" }, new[]{ "Temperature", "CandidateCount", "TopP", "TopK" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse), global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse.Parser, new[]{ "Candidates", "Messages", "Filters" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.Message), global::Google.Ai.Generativelanguage.V1Beta2.Message.Parser, new[]{ "Author", "Content", "CitationMetadata" }, new[]{ "CitationMetadata" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt), global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt.Parser, new[]{ "Context", "Examples", "Messages" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.Example), global::Google.Ai.Generativelanguage.V1Beta2.Example.Parser, new[]{ "Input", "Output" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest), global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest.Parser, new[]{ "Model", "Prompt" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse), global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse.Parser, new[]{ "TokenCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Request to generate a message response from the model.
  /// </summary>
  public sealed partial class GenerateMessageRequest : pb::IMessage<GenerateMessageRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateMessageRequest> _parser = new pb::MessageParser<GenerateMessageRequest>(() => new GenerateMessageRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateMessageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.DiscussServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateMessageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateMessageRequest(GenerateMessageRequest other) : this() {
      _hasBits0 = other._hasBits0;
      model_ = other.model_;
      prompt_ = other.prompt_ != null ? other.prompt_.Clone() : null;
      temperature_ = other.temperature_;
      candidateCount_ = other.candidateCount_;
      topP_ = other.topP_;
      topK_ = other.topK_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateMessageRequest Clone() {
      return new GenerateMessageRequest(this);
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 1;
    private string model_ = "";
    /// <summary>
    /// Required. The name of the model to use.
    ///
    /// Format: `name=models/{model}`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prompt" field.</summary>
    public const int PromptFieldNumber = 2;
    private global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt prompt_;
    /// <summary>
    /// Required. The structured textual input given to the model as a prompt.
    ///
    /// Given a
    /// prompt, the model will return what it predicts is the next message in the
    /// discussion.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt Prompt {
      get { return prompt_; }
      set {
        prompt_ = value;
      }
    }

    /// <summary>Field number for the "temperature" field.</summary>
    public const int TemperatureFieldNumber = 3;
    private float temperature_;
    /// <summary>
    /// Optional. Controls the randomness of the output.
    ///
    /// Values can range over `[0.0,1.0]`,
    /// inclusive. A value closer to `1.0` will produce responses that are more
    /// varied, while a value closer to `0.0` will typically result in
    /// less surprising responses from the model.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Temperature {
      get { if ((_hasBits0 & 1) != 0) { return temperature_; } else { return 0F; } }
      set {
        _hasBits0 |= 1;
        temperature_ = value;
      }
    }
    /// <summary>Gets whether the "temperature" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTemperature {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "temperature" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTemperature() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "candidate_count" field.</summary>
    public const int CandidateCountFieldNumber = 4;
    private int candidateCount_;
    /// <summary>
    /// Optional. The number of generated response messages to return.
    ///
    /// This value must be between
    /// `[1, 8]`, inclusive. If unset, this will default to `1`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CandidateCount {
      get { if ((_hasBits0 & 2) != 0) { return candidateCount_; } else { return 0; } }
      set {
        _hasBits0 |= 2;
        candidateCount_ = value;
      }
    }
    /// <summary>Gets whether the "candidate_count" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCandidateCount {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "candidate_count" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCandidateCount() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "top_p" field.</summary>
    public const int TopPFieldNumber = 5;
    private float topP_;
    /// <summary>
    /// Optional. The maximum cumulative probability of tokens to consider when
    /// sampling.
    ///
    /// The model uses combined Top-k and nucleus sampling.
    ///
    /// Nucleus sampling considers the smallest set of tokens whose probability
    /// sum is at least `top_p`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TopP {
      get { if ((_hasBits0 & 4) != 0) { return topP_; } else { return 0F; } }
      set {
        _hasBits0 |= 4;
        topP_ = value;
      }
    }
    /// <summary>Gets whether the "top_p" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTopP {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "top_p" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTopP() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "top_k" field.</summary>
    public const int TopKFieldNumber = 6;
    private int topK_;
    /// <summary>
    /// Optional. The maximum number of tokens to consider when sampling.
    ///
    /// The model uses combined Top-k and nucleus sampling.
    ///
    /// Top-k sampling considers the set of `top_k` most probable tokens.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TopK {
      get { if ((_hasBits0 & 8) != 0) { return topK_; } else { return 0; } }
      set {
        _hasBits0 |= 8;
        topK_ = value;
      }
    }
    /// <summary>Gets whether the "top_k" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTopK {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "top_k" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTopK() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateMessageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateMessageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Model != other.Model) return false;
      if (!object.Equals(Prompt, other.Prompt)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Temperature, other.Temperature)) return false;
      if (CandidateCount != other.CandidateCount) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TopP, other.TopP)) return false;
      if (TopK != other.TopK) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      if (prompt_ != null) hash ^= Prompt.GetHashCode();
      if (HasTemperature) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Temperature);
      if (HasCandidateCount) hash ^= CandidateCount.GetHashCode();
      if (HasTopP) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TopP);
      if (HasTopK) hash ^= TopK.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Model.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Model);
      }
      if (prompt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Prompt);
      }
      if (HasTemperature) {
        output.WriteRawTag(29);
        output.WriteFloat(Temperature);
      }
      if (HasCandidateCount) {
        output.WriteRawTag(32);
        output.WriteInt32(CandidateCount);
      }
      if (HasTopP) {
        output.WriteRawTag(45);
        output.WriteFloat(TopP);
      }
      if (HasTopK) {
        output.WriteRawTag(48);
        output.WriteInt32(TopK);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Model.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Model);
      }
      if (prompt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Prompt);
      }
      if (HasTemperature) {
        output.WriteRawTag(29);
        output.WriteFloat(Temperature);
      }
      if (HasCandidateCount) {
        output.WriteRawTag(32);
        output.WriteInt32(CandidateCount);
      }
      if (HasTopP) {
        output.WriteRawTag(45);
        output.WriteFloat(TopP);
      }
      if (HasTopK) {
        output.WriteRawTag(48);
        output.WriteInt32(TopK);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      if (prompt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Prompt);
      }
      if (HasTemperature) {
        size += 1 + 4;
      }
      if (HasCandidateCount) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CandidateCount);
      }
      if (HasTopP) {
        size += 1 + 4;
      }
      if (HasTopK) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopK);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateMessageRequest other) {
      if (other == null) {
        return;
      }
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      if (other.prompt_ != null) {
        if (prompt_ == null) {
          Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt();
        }
        Prompt.MergeFrom(other.Prompt);
      }
      if (other.HasTemperature) {
        Temperature = other.Temperature;
      }
      if (other.HasCandidateCount) {
        CandidateCount = other.CandidateCount;
      }
      if (other.HasTopP) {
        TopP = other.TopP;
      }
      if (other.HasTopK) {
        TopK = other.TopK;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Model = input.ReadString();
            break;
          }
          case 18: {
            if (prompt_ == null) {
              Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt();
            }
            input.ReadMessage(Prompt);
            break;
          }
          case 29: {
            Temperature = input.ReadFloat();
            break;
          }
          case 32: {
            CandidateCount = input.ReadInt32();
            break;
          }
          case 45: {
            TopP = input.ReadFloat();
            break;
          }
          case 48: {
            TopK = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Model = input.ReadString();
            break;
          }
          case 18: {
            if (prompt_ == null) {
              Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt();
            }
            input.ReadMessage(Prompt);
            break;
          }
          case 29: {
            Temperature = input.ReadFloat();
            break;
          }
          case 32: {
            CandidateCount = input.ReadInt32();
            break;
          }
          case 45: {
            TopP = input.ReadFloat();
            break;
          }
          case 48: {
            TopK = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response from the model.
  ///
  /// This includes candidate messages and
  /// conversation history in the form of chronologically-ordered messages.
  /// </summary>
  public sealed partial class GenerateMessageResponse : pb::IMessage<GenerateMessageResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateMessageResponse> _parser = new pb::MessageParser<GenerateMessageResponse>(() => new GenerateMessageResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateMessageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.DiscussServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateMessageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateMessageResponse(GenerateMessageResponse other) : this() {
      candidates_ = other.candidates_.Clone();
      messages_ = other.messages_.Clone();
      filters_ = other.filters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateMessageResponse Clone() {
      return new GenerateMessageResponse(this);
    }

    /// <summary>Field number for the "candidates" field.</summary>
    public const int CandidatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.Message> _repeated_candidates_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Ai.Generativelanguage.V1Beta2.Message.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message> candidates_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message>();
    /// <summary>
    /// Candidate response messages from the model.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message> Candidates {
      get { return candidates_; }
    }

    /// <summary>Field number for the "messages" field.</summary>
    public const int MessagesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.Message> _repeated_messages_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Ai.Generativelanguage.V1Beta2.Message.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message> messages_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message>();
    /// <summary>
    /// The conversation history used by the model.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message> Messages {
      get { return messages_; }
    }

    /// <summary>Field number for the "filters" field.</summary>
    public const int FiltersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter> _repeated_filters_codec
        = pb::FieldCodec.ForMessage(26, global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter> filters_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter>();
    /// <summary>
    /// A set of content filtering metadata for the prompt and response
    /// text.
    ///
    /// This indicates which `SafetyCategory`(s) blocked a
    /// candidate from this response, the lowest `HarmProbability`
    /// that triggered a block, and the HarmThreshold setting for that category.
    /// This indicates the smallest change to the `SafetySettings` that would be
    /// necessary to unblock at least 1 response.
    ///
    /// The blocking is configured by the `SafetySettings` in the request (or the
    /// default `SafetySettings` of the API).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter> Filters {
      get { return filters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateMessageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateMessageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!candidates_.Equals(other.candidates_)) return false;
      if(!messages_.Equals(other.messages_)) return false;
      if(!filters_.Equals(other.filters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= candidates_.GetHashCode();
      hash ^= messages_.GetHashCode();
      hash ^= filters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      candidates_.WriteTo(output, _repeated_candidates_codec);
      messages_.WriteTo(output, _repeated_messages_codec);
      filters_.WriteTo(output, _repeated_filters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      candidates_.WriteTo(ref output, _repeated_candidates_codec);
      messages_.WriteTo(ref output, _repeated_messages_codec);
      filters_.WriteTo(ref output, _repeated_filters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += candidates_.CalculateSize(_repeated_candidates_codec);
      size += messages_.CalculateSize(_repeated_messages_codec);
      size += filters_.CalculateSize(_repeated_filters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateMessageResponse other) {
      if (other == null) {
        return;
      }
      candidates_.Add(other.candidates_);
      messages_.Add(other.messages_);
      filters_.Add(other.filters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            candidates_.AddEntriesFrom(input, _repeated_candidates_codec);
            break;
          }
          case 18: {
            messages_.AddEntriesFrom(input, _repeated_messages_codec);
            break;
          }
          case 26: {
            filters_.AddEntriesFrom(input, _repeated_filters_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            candidates_.AddEntriesFrom(ref input, _repeated_candidates_codec);
            break;
          }
          case 18: {
            messages_.AddEntriesFrom(ref input, _repeated_messages_codec);
            break;
          }
          case 26: {
            filters_.AddEntriesFrom(ref input, _repeated_filters_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The base unit of structured text.
  ///
  /// A `Message` includes an `author` and the `content` of
  /// the `Message`.
  ///
  /// The `author` is used to tag messages when they are fed to the
  /// model as text.
  /// </summary>
  public sealed partial class Message : pb::IMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.DiscussServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      author_ = other.author_;
      content_ = other.content_;
      citationMetadata_ = other.citationMetadata_ != null ? other.citationMetadata_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "author" field.</summary>
    public const int AuthorFieldNumber = 1;
    private string author_ = "";
    /// <summary>
    /// Optional. The author of this Message.
    ///
    /// This serves as a key for tagging
    /// the content of this Message when it is fed to the model as text.
    ///
    /// The author can be any alphanumeric string.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Author {
      get { return author_; }
      set {
        author_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 2;
    private string content_ = "";
    /// <summary>
    /// Required. The text content of the structured `Message`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "citation_metadata" field.</summary>
    public const int CitationMetadataFieldNumber = 3;
    private global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata citationMetadata_;
    /// <summary>
    /// Output only. Citation information for model-generated `content` in this
    /// `Message`.
    ///
    /// If this `Message` was generated as output from the model, this field may be
    /// populated with attribution information for any text included in the
    /// `content`. This field is used only on output.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata CitationMetadata {
      get { return citationMetadata_; }
      set {
        citationMetadata_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Author != other.Author) return false;
      if (Content != other.Content) return false;
      if (!object.Equals(CitationMetadata, other.CitationMetadata)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Author.Length != 0) hash ^= Author.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (citationMetadata_ != null) hash ^= CitationMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Author.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Author);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Content);
      }
      if (citationMetadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CitationMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Author.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Author);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Content);
      }
      if (citationMetadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CitationMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Author.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Author);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (citationMetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CitationMetadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.Author.Length != 0) {
        Author = other.Author;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.citationMetadata_ != null) {
        if (citationMetadata_ == null) {
          CitationMetadata = new global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata();
        }
        CitationMetadata.MergeFrom(other.CitationMetadata);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Author = input.ReadString();
            break;
          }
          case 18: {
            Content = input.ReadString();
            break;
          }
          case 26: {
            if (citationMetadata_ == null) {
              CitationMetadata = new global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata();
            }
            input.ReadMessage(CitationMetadata);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Author = input.ReadString();
            break;
          }
          case 18: {
            Content = input.ReadString();
            break;
          }
          case 26: {
            if (citationMetadata_ == null) {
              CitationMetadata = new global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata();
            }
            input.ReadMessage(CitationMetadata);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// All of the structured input text passed to the model as a prompt.
  ///
  /// A `MessagePrompt` contains a structured set of fields that provide context
  /// for the conversation, examples of user input/model output message pairs that
  /// prime the model to respond in different ways, and the conversation history
  /// or list of messages representing the alternating turns of the conversation
  /// between the user and the model.
  /// </summary>
  public sealed partial class MessagePrompt : pb::IMessage<MessagePrompt>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessagePrompt> _parser = new pb::MessageParser<MessagePrompt>(() => new MessagePrompt());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessagePrompt> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.DiscussServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessagePrompt() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessagePrompt(MessagePrompt other) : this() {
      context_ = other.context_;
      examples_ = other.examples_.Clone();
      messages_ = other.messages_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessagePrompt Clone() {
      return new MessagePrompt(this);
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 1;
    private string context_ = "";
    /// <summary>
    /// Optional. Text that should be provided to the model first to ground the
    /// response.
    ///
    /// If not empty, this `context` will be given to the model first before the
    /// `examples` and `messages`. When using a `context` be sure to provide it
    /// with every request to maintain continuity.
    ///
    /// This field can be a description of your prompt to the model to help provide
    /// context and guide the responses. Examples: "Translate the phrase from
    /// English to French." or "Given a statement, classify the sentiment as happy,
    /// sad or neutral."
    ///
    /// Anything included in this field will take precedence over message history
    /// if the total input size exceeds the model's `input_token_limit` and the
    /// input request is truncated.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Context {
      get { return context_; }
      set {
        context_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "examples" field.</summary>
    public const int ExamplesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.Example> _repeated_examples_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Ai.Generativelanguage.V1Beta2.Example.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Example> examples_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Example>();
    /// <summary>
    /// Optional. Examples of what the model should generate.
    ///
    /// This includes both user input and the response that the model should
    /// emulate.
    ///
    /// These `examples` are treated identically to conversation messages except
    /// that they take precedence over the history in `messages`:
    /// If the total input size exceeds the model's `input_token_limit` the input
    /// will be truncated. Items will be dropped from `messages` before `examples`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Example> Examples {
      get { return examples_; }
    }

    /// <summary>Field number for the "messages" field.</summary>
    public const int MessagesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.Message> _repeated_messages_codec
        = pb::FieldCodec.ForMessage(26, global::Google.Ai.Generativelanguage.V1Beta2.Message.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message> messages_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message>();
    /// <summary>
    /// Required. A snapshot of the recent conversation history sorted
    /// chronologically.
    ///
    /// Turns alternate between two authors.
    ///
    /// If the total input size exceeds the model's `input_token_limit` the input
    /// will be truncated: The oldest items will be dropped from `messages`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.Message> Messages {
      get { return messages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessagePrompt);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessagePrompt other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Context != other.Context) return false;
      if(!examples_.Equals(other.examples_)) return false;
      if(!messages_.Equals(other.messages_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Context.Length != 0) hash ^= Context.GetHashCode();
      hash ^= examples_.GetHashCode();
      hash ^= messages_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Context.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Context);
      }
      examples_.WriteTo(output, _repeated_examples_codec);
      messages_.WriteTo(output, _repeated_messages_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Context.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Context);
      }
      examples_.WriteTo(ref output, _repeated_examples_codec);
      messages_.WriteTo(ref output, _repeated_messages_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Context.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Context);
      }
      size += examples_.CalculateSize(_repeated_examples_codec);
      size += messages_.CalculateSize(_repeated_messages_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessagePrompt other) {
      if (other == null) {
        return;
      }
      if (other.Context.Length != 0) {
        Context = other.Context;
      }
      examples_.Add(other.examples_);
      messages_.Add(other.messages_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Context = input.ReadString();
            break;
          }
          case 18: {
            examples_.AddEntriesFrom(input, _repeated_examples_codec);
            break;
          }
          case 26: {
            messages_.AddEntriesFrom(input, _repeated_messages_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Context = input.ReadString();
            break;
          }
          case 18: {
            examples_.AddEntriesFrom(ref input, _repeated_examples_codec);
            break;
          }
          case 26: {
            messages_.AddEntriesFrom(ref input, _repeated_messages_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// An input/output example used to instruct the Model.
  ///
  /// It demonstrates how the model should respond or format its response.
  /// </summary>
  public sealed partial class Example : pb::IMessage<Example>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Example> _parser = new pb::MessageParser<Example>(() => new Example());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Example> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.DiscussServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Example() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Example(Example other) : this() {
      input_ = other.input_ != null ? other.input_.Clone() : null;
      output_ = other.output_ != null ? other.output_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Example Clone() {
      return new Example(this);
    }

    /// <summary>Field number for the "input" field.</summary>
    public const int InputFieldNumber = 1;
    private global::Google.Ai.Generativelanguage.V1Beta2.Message input_;
    /// <summary>
    /// An example of an input `Message` from the user.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.Message Input {
      get { return input_; }
      set {
        input_ = value;
      }
    }

    /// <summary>Field number for the "output" field.</summary>
    public const int OutputFieldNumber = 2;
    private global::Google.Ai.Generativelanguage.V1Beta2.Message output_;
    /// <summary>
    /// An example of what the model should output given the input.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.Message Output {
      get { return output_; }
      set {
        output_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Example);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Example other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Input, other.Input)) return false;
      if (!object.Equals(Output, other.Output)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (input_ != null) hash ^= Input.GetHashCode();
      if (output_ != null) hash ^= Output.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (input_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Input);
      }
      if (output_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (input_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Input);
      }
      if (output_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (input_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Input);
      }
      if (output_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Output);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Example other) {
      if (other == null) {
        return;
      }
      if (other.input_ != null) {
        if (input_ == null) {
          Input = new global::Google.Ai.Generativelanguage.V1Beta2.Message();
        }
        Input.MergeFrom(other.Input);
      }
      if (other.output_ != null) {
        if (output_ == null) {
          Output = new global::Google.Ai.Generativelanguage.V1Beta2.Message();
        }
        Output.MergeFrom(other.Output);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (input_ == null) {
              Input = new global::Google.Ai.Generativelanguage.V1Beta2.Message();
            }
            input.ReadMessage(Input);
            break;
          }
          case 18: {
            if (output_ == null) {
              Output = new global::Google.Ai.Generativelanguage.V1Beta2.Message();
            }
            input.ReadMessage(Output);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (input_ == null) {
              Input = new global::Google.Ai.Generativelanguage.V1Beta2.Message();
            }
            input.ReadMessage(Input);
            break;
          }
          case 18: {
            if (output_ == null) {
              Output = new global::Google.Ai.Generativelanguage.V1Beta2.Message();
            }
            input.ReadMessage(Output);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Counts the number of tokens in the `prompt` sent to a model.
  ///
  /// Models may tokenize text differently, so each model may return a different
  /// `token_count`.
  /// </summary>
  public sealed partial class CountMessageTokensRequest : pb::IMessage<CountMessageTokensRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CountMessageTokensRequest> _parser = new pb::MessageParser<CountMessageTokensRequest>(() => new CountMessageTokensRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CountMessageTokensRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.DiscussServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CountMessageTokensRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CountMessageTokensRequest(CountMessageTokensRequest other) : this() {
      model_ = other.model_;
      prompt_ = other.prompt_ != null ? other.prompt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CountMessageTokensRequest Clone() {
      return new CountMessageTokensRequest(this);
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 1;
    private string model_ = "";
    /// <summary>
    /// Required. The model's resource name. This serves as an ID for the Model to
    /// use.
    ///
    /// This name should match a model name returned by the `ListModels` method.
    ///
    /// Format: `models/{model}`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prompt" field.</summary>
    public const int PromptFieldNumber = 2;
    private global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt prompt_;
    /// <summary>
    /// Required. The prompt, whose token count is to be returned.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt Prompt {
      get { return prompt_; }
      set {
        prompt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CountMessageTokensRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CountMessageTokensRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Model != other.Model) return false;
      if (!object.Equals(Prompt, other.Prompt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      if (prompt_ != null) hash ^= Prompt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Model.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Model);
      }
      if (prompt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Prompt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Model.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Model);
      }
      if (prompt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Prompt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      if (prompt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Prompt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CountMessageTokensRequest other) {
      if (other == null) {
        return;
      }
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      if (other.prompt_ != null) {
        if (prompt_ == null) {
          Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt();
        }
        Prompt.MergeFrom(other.Prompt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Model = input.ReadString();
            break;
          }
          case 18: {
            if (prompt_ == null) {
              Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt();
            }
            input.ReadMessage(Prompt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Model = input.ReadString();
            break;
          }
          case 18: {
            if (prompt_ == null) {
              Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.MessagePrompt();
            }
            input.ReadMessage(Prompt);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// A response from `CountMessageTokens`.
  ///
  /// It returns the model's `token_count` for the `prompt`.
  /// </summary>
  public sealed partial class CountMessageTokensResponse : pb::IMessage<CountMessageTokensResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CountMessageTokensResponse> _parser = new pb::MessageParser<CountMessageTokensResponse>(() => new CountMessageTokensResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CountMessageTokensResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.DiscussServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CountMessageTokensResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CountMessageTokensResponse(CountMessageTokensResponse other) : this() {
      tokenCount_ = other.tokenCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CountMessageTokensResponse Clone() {
      return new CountMessageTokensResponse(this);
    }

    /// <summary>Field number for the "token_count" field.</summary>
    public const int TokenCountFieldNumber = 1;
    private int tokenCount_;
    /// <summary>
    /// The number of tokens that the `model` tokenizes the `prompt` into.
    ///
    /// Always non-negative.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TokenCount {
      get { return tokenCount_; }
      set {
        tokenCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CountMessageTokensResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CountMessageTokensResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TokenCount != other.TokenCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TokenCount != 0) hash ^= TokenCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TokenCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TokenCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TokenCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TokenCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TokenCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TokenCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CountMessageTokensResponse other) {
      if (other == null) {
        return;
      }
      if (other.TokenCount != 0) {
        TokenCount = other.TokenCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TokenCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TokenCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
