// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ai/generativelanguage/v1beta2/discuss_service.proto
// </auto-generated>
// Original file comments:
// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Google.Ai.Generativelanguage.V1Beta2 {
  /// <summary>
  /// An API for using Generative Language Models (GLMs) in dialog applications.
  ///
  /// Also known as large language models (LLMs), this API provides models that
  /// are trained for multi-turn dialog.
  /// </summary>
  public static partial class DiscussService
  {
    static readonly string __ServiceName = "google.ai.generativelanguage.v1beta2.DiscussService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest> __Marshaller_google_ai_generativelanguage_v1beta2_GenerateMessageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse> __Marshaller_google_ai_generativelanguage_v1beta2_GenerateMessageResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest> __Marshaller_google_ai_generativelanguage_v1beta2_CountMessageTokensRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse> __Marshaller_google_ai_generativelanguage_v1beta2_CountMessageTokensResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest, global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse> __Method_GenerateMessage = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest, global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GenerateMessage",
        __Marshaller_google_ai_generativelanguage_v1beta2_GenerateMessageRequest,
        __Marshaller_google_ai_generativelanguage_v1beta2_GenerateMessageResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest, global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse> __Method_CountMessageTokens = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest, global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CountMessageTokens",
        __Marshaller_google_ai_generativelanguage_v1beta2_CountMessageTokensRequest,
        __Marshaller_google_ai_generativelanguage_v1beta2_CountMessageTokensResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.DiscussServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DiscussService</summary>
    [grpc::BindServiceMethod(typeof(DiscussService), "BindService")]
    public abstract partial class DiscussServiceBase
    {
      /// <summary>
      /// Generates a response from the model given an input `MessagePrompt`.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse> GenerateMessage(global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Runs a model's tokenizer on a string and returns the token count.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse> CountMessageTokens(global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DiscussService</summary>
    public partial class DiscussServiceClient : grpc::ClientBase<DiscussServiceClient>
    {
      /// <summary>Creates a new client for DiscussService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DiscussServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DiscussService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DiscussServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DiscussServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DiscussServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Generates a response from the model given an input `MessagePrompt`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse GenerateMessage(global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a response from the model given an input `MessagePrompt`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse GenerateMessage(global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GenerateMessage, null, options, request);
      }
      /// <summary>
      /// Generates a response from the model given an input `MessagePrompt`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse> GenerateMessageAsync(global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a response from the model given an input `MessagePrompt`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse> GenerateMessageAsync(global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GenerateMessage, null, options, request);
      }
      /// <summary>
      /// Runs a model's tokenizer on a string and returns the token count.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse CountMessageTokens(global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CountMessageTokens(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Runs a model's tokenizer on a string and returns the token count.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse CountMessageTokens(global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CountMessageTokens, null, options, request);
      }
      /// <summary>
      /// Runs a model's tokenizer on a string and returns the token count.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse> CountMessageTokensAsync(global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CountMessageTokensAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Runs a model's tokenizer on a string and returns the token count.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse> CountMessageTokensAsync(global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CountMessageTokens, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DiscussServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DiscussServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DiscussServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GenerateMessage, serviceImpl.GenerateMessage)
          .AddMethod(__Method_CountMessageTokens, serviceImpl.CountMessageTokens).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DiscussServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GenerateMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageRequest, global::Google.Ai.Generativelanguage.V1Beta2.GenerateMessageResponse>(serviceImpl.GenerateMessage));
      serviceBinder.AddMethod(__Method_CountMessageTokens, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensRequest, global::Google.Ai.Generativelanguage.V1Beta2.CountMessageTokensResponse>(serviceImpl.CountMessageTokens));
    }

  }
}
#endregion
