// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ai/generativelanguage/v1beta2/safety.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Ai.Generativelanguage.V1Beta2 {

  /// <summary>Holder for reflection information generated from google/ai/generativelanguage/v1beta2/safety.proto</summary>
  public static partial class SafetyReflection {

    #region Descriptor
    /// <summary>File descriptor for google/ai/generativelanguage/v1beta2/safety.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SafetyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFnb29nbGUvYWkvZ2VuZXJhdGl2ZWxhbmd1YWdlL3YxYmV0YTIvc2FmZXR5",
            "LnByb3RvEiRnb29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIa",
            "H2dvb2dsZS9hcGkvZmllbGRfYmVoYXZpb3IucHJvdG8izAEKDUNvbnRlbnRG",
            "aWx0ZXISUQoGcmVhc29uGAEgASgOMkEuZ29vZ2xlLmFpLmdlbmVyYXRpdmVs",
            "YW5ndWFnZS52MWJldGEyLkNvbnRlbnRGaWx0ZXIuQmxvY2tlZFJlYXNvbhIU",
            "CgdtZXNzYWdlGAIgASgJSACIAQEiRgoNQmxvY2tlZFJlYXNvbhIeChpCTE9D",
            "S0VEX1JFQVNPTl9VTlNQRUNJRklFRBAAEgoKBlNBRkVUWRABEgkKBU9USEVS",
            "EAJCCgoIX21lc3NhZ2UimgEKDlNhZmV0eUZlZWRiYWNrEkIKBnJhdGluZxgB",
            "IAEoCzIyLmdvb2dsZS5haS5nZW5lcmF0aXZlbGFuZ3VhZ2UudjFiZXRhMi5T",
            "YWZldHlSYXRpbmcSRAoHc2V0dGluZxgCIAEoCzIzLmdvb2dsZS5haS5nZW5l",
            "cmF0aXZlbGFuZ3VhZ2UudjFiZXRhMi5TYWZldHlTZXR0aW5nIpsCCgxTYWZl",
            "dHlSYXRpbmcSSQoIY2F0ZWdvcnkYAyABKA4yMi5nb29nbGUuYWkuZ2VuZXJh",
            "dGl2ZWxhbmd1YWdlLnYxYmV0YTIuSGFybUNhdGVnb3J5QgPgQQISXAoLcHJv",
            "YmFiaWxpdHkYBCABKA4yQi5nb29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdl",
            "LnYxYmV0YTIuU2FmZXR5UmF0aW5nLkhhcm1Qcm9iYWJpbGl0eUID4EECImIK",
            "D0hhcm1Qcm9iYWJpbGl0eRIgChxIQVJNX1BST0JBQklMSVRZX1VOU1BFQ0lG",
            "SUVEEAASDgoKTkVHTElHSUJMRRABEgcKA0xPVxACEgoKBk1FRElVTRADEggK",
            "BEhJR0gQBCLRAgoNU2FmZXR5U2V0dGluZxJJCghjYXRlZ29yeRgDIAEoDjIy",
            "Lmdvb2dsZS5haS5nZW5lcmF0aXZlbGFuZ3VhZ2UudjFiZXRhMi5IYXJtQ2F0",
            "ZWdvcnlCA+BBAhJeCgl0aHJlc2hvbGQYBCABKA4yRi5nb29nbGUuYWkuZ2Vu",
            "ZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuU2FmZXR5U2V0dGluZy5IYXJtQmxv",
            "Y2tUaHJlc2hvbGRCA+BBAiKUAQoSSGFybUJsb2NrVGhyZXNob2xkEiQKIEhB",
            "Uk1fQkxPQ0tfVEhSRVNIT0xEX1VOU1BFQ0lGSUVEEAASFwoTQkxPQ0tfTE9X",
            "X0FORF9BQk9WRRABEhoKFkJMT0NLX01FRElVTV9BTkRfQUJPVkUQAhITCg9C",
            "TE9DS19PTkxZX0hJR0gQAxIOCgpCTE9DS19OT05FEAQq1QEKDEhhcm1DYXRl",
            "Z29yeRIdChlIQVJNX0NBVEVHT1JZX1VOU1BFQ0lGSUVEEAASHAoYSEFSTV9D",
            "QVRFR09SWV9ERVJPR0FUT1JZEAESGgoWSEFSTV9DQVRFR09SWV9UT1hJQ0lU",
            "WRACEhoKFkhBUk1fQ0FURUdPUllfVklPTEVOQ0UQAxIYChRIQVJNX0NBVEVH",
            "T1JZX1NFWFVBTBAEEhkKFUhBUk1fQ0FURUdPUllfTUVESUNBTBAFEhsKF0hB",
            "Uk1fQ0FURUdPUllfREFOR0VST1VTEAZCkQEKKGNvbS5nb29nbGUuYWkuZ2Vu",
            "ZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTJCC1NhZmV0eVByb3RvUAFaVmdvb2ds",
            "ZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvYWkvZ2VuZXJhdGl2",
            "ZWxhbmd1YWdlL3YxYmV0YTI7Z2VuZXJhdGl2ZWxhbmd1YWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.FieldBehaviorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter), global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Parser, new[]{ "Reason", "Message" }, new[]{ "Message" }, new[]{ typeof(global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.SafetyFeedback), global::Google.Ai.Generativelanguage.V1Beta2.SafetyFeedback.Parser, new[]{ "Rating", "Setting" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating), global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Parser, new[]{ "Category", "Probability" }, null, new[]{ typeof(global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting), global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Parser, new[]{ "Category", "Threshold" }, null, new[]{ typeof(global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold) }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// The category of a rating.
  ///
  /// These categories cover various kinds of harms that developers
  /// may wish to adjust.
  /// </summary>
  public enum HarmCategory {
    /// <summary>
    /// Category is unspecified.
    /// </summary>
    [pbr::OriginalName("HARM_CATEGORY_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Negative or harmful comments targeting identity and/or protected attribute.
    /// </summary>
    [pbr::OriginalName("HARM_CATEGORY_DEROGATORY")] Derogatory = 1,
    /// <summary>
    /// Content that is rude, disrepspectful, or profane.
    /// </summary>
    [pbr::OriginalName("HARM_CATEGORY_TOXICITY")] Toxicity = 2,
    /// <summary>
    /// Describes scenarios depictng violence against an individual or group, or
    /// general descriptions of gore.
    /// </summary>
    [pbr::OriginalName("HARM_CATEGORY_VIOLENCE")] Violence = 3,
    /// <summary>
    /// Contains references to sexual acts or other lewd content.
    /// </summary>
    [pbr::OriginalName("HARM_CATEGORY_SEXUAL")] Sexual = 4,
    /// <summary>
    /// Promotes unchecked medical advice.
    /// </summary>
    [pbr::OriginalName("HARM_CATEGORY_MEDICAL")] Medical = 5,
    /// <summary>
    /// Dangerous content that promotes, facilitates, or encourages harmful acts.
    /// </summary>
    [pbr::OriginalName("HARM_CATEGORY_DANGEROUS")] Dangerous = 6,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Content filtering metadata associated with processing a single request.
  ///
  /// ContentFilter contains a reason and an optional supporting string. The reason
  /// may be unspecified.
  /// </summary>
  public sealed partial class ContentFilter : pb::IMessage<ContentFilter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ContentFilter> _parser = new pb::MessageParser<ContentFilter>(() => new ContentFilter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ContentFilter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.SafetyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContentFilter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContentFilter(ContentFilter other) : this() {
      reason_ = other.reason_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContentFilter Clone() {
      return new ContentFilter(this);
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 1;
    private global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason reason_ = global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason.Unspecified;
    /// <summary>
    /// The reason content was blocked during request processing.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_;
    /// <summary>
    /// A string that describes the filtering behavior in more detail.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_ ?? ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "message" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMessage {
      get { return message_ != null; }
    }
    /// <summary>Clears the value of the "message" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ContentFilter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ContentFilter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Reason != other.Reason) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Reason != global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason.Unspecified) hash ^= Reason.GetHashCode();
      if (HasMessage) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Reason != global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Reason);
      }
      if (HasMessage) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Reason != global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Reason);
      }
      if (HasMessage) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Reason != global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      if (HasMessage) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ContentFilter other) {
      if (other == null) {
        return;
      }
      if (other.Reason != global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason.Unspecified) {
        Reason = other.Reason;
      }
      if (other.HasMessage) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Reason = (global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Reason = (global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Types.BlockedReason) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ContentFilter message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// A list of reasons why content may have been blocked.
      /// </summary>
      public enum BlockedReason {
        /// <summary>
        /// A blocked reason was not specified.
        /// </summary>
        [pbr::OriginalName("BLOCKED_REASON_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// Content was blocked by safety settings.
        /// </summary>
        [pbr::OriginalName("SAFETY")] Safety = 1,
        /// <summary>
        /// Content was blocked, but the reason is uncategorized.
        /// </summary>
        [pbr::OriginalName("OTHER")] Other = 2,
      }

    }
    #endregion

  }

  /// <summary>
  /// Safety feedback for an entire request.
  ///
  /// This field is populated if content in the input and/or response is blocked
  /// due to safety settings. SafetyFeedback may not exist for every HarmCategory.
  /// Each SafetyFeedback will return the safety settings used by the request as
  /// well as the lowest HarmProbability that should be allowed in order to return
  /// a result.
  /// </summary>
  public sealed partial class SafetyFeedback : pb::IMessage<SafetyFeedback>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SafetyFeedback> _parser = new pb::MessageParser<SafetyFeedback>(() => new SafetyFeedback());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SafetyFeedback> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.SafetyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetyFeedback() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetyFeedback(SafetyFeedback other) : this() {
      rating_ = other.rating_ != null ? other.rating_.Clone() : null;
      setting_ = other.setting_ != null ? other.setting_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetyFeedback Clone() {
      return new SafetyFeedback(this);
    }

    /// <summary>Field number for the "rating" field.</summary>
    public const int RatingFieldNumber = 1;
    private global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating rating_;
    /// <summary>
    /// Safety rating evaluated from content.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating Rating {
      get { return rating_; }
      set {
        rating_ = value;
      }
    }

    /// <summary>Field number for the "setting" field.</summary>
    public const int SettingFieldNumber = 2;
    private global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting setting_;
    /// <summary>
    /// Safety settings applied to the request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting Setting {
      get { return setting_; }
      set {
        setting_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SafetyFeedback);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SafetyFeedback other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Rating, other.Rating)) return false;
      if (!object.Equals(Setting, other.Setting)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (rating_ != null) hash ^= Rating.GetHashCode();
      if (setting_ != null) hash ^= Setting.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (rating_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Rating);
      }
      if (setting_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Setting);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (rating_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Rating);
      }
      if (setting_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Setting);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (rating_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rating);
      }
      if (setting_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Setting);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SafetyFeedback other) {
      if (other == null) {
        return;
      }
      if (other.rating_ != null) {
        if (rating_ == null) {
          Rating = new global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating();
        }
        Rating.MergeFrom(other.Rating);
      }
      if (other.setting_ != null) {
        if (setting_ == null) {
          Setting = new global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting();
        }
        Setting.MergeFrom(other.Setting);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (rating_ == null) {
              Rating = new global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating();
            }
            input.ReadMessage(Rating);
            break;
          }
          case 18: {
            if (setting_ == null) {
              Setting = new global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting();
            }
            input.ReadMessage(Setting);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (rating_ == null) {
              Rating = new global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating();
            }
            input.ReadMessage(Rating);
            break;
          }
          case 18: {
            if (setting_ == null) {
              Setting = new global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting();
            }
            input.ReadMessage(Setting);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Safety rating for a piece of content.
  ///
  /// The safety rating contains the category of harm and the
  /// harm probability level in that category for a piece of content.
  /// Content is classified for safety across a number of
  /// harm categories and the probability of the harm classification is included
  /// here.
  /// </summary>
  public sealed partial class SafetyRating : pb::IMessage<SafetyRating>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SafetyRating> _parser = new pb::MessageParser<SafetyRating>(() => new SafetyRating());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SafetyRating> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.SafetyReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetyRating() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetyRating(SafetyRating other) : this() {
      category_ = other.category_;
      probability_ = other.probability_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetyRating Clone() {
      return new SafetyRating(this);
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 3;
    private global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory category_ = global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified;
    /// <summary>
    /// Required. The category for this rating.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    /// <summary>Field number for the "probability" field.</summary>
    public const int ProbabilityFieldNumber = 4;
    private global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability probability_ = global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability.Unspecified;
    /// <summary>
    /// Required. The probability of harm for this content.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability Probability {
      get { return probability_; }
      set {
        probability_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SafetyRating);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SafetyRating other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Category != other.Category) return false;
      if (Probability != other.Probability) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) hash ^= Category.GetHashCode();
      if (Probability != global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability.Unspecified) hash ^= Probability.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Category);
      }
      if (Probability != global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Probability);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Category);
      }
      if (Probability != global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Probability);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      if (Probability != global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Probability);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SafetyRating other) {
      if (other == null) {
        return;
      }
      if (other.Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) {
        Category = other.Category;
      }
      if (other.Probability != global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability.Unspecified) {
        Probability = other.Probability;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            Category = (global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory) input.ReadEnum();
            break;
          }
          case 32: {
            Probability = (global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            Category = (global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory) input.ReadEnum();
            break;
          }
          case 32: {
            Probability = (global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Types.HarmProbability) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SafetyRating message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// The probability that a piece of content is harmful.
      ///
      /// The classification system gives the probability of the content being
      /// unsafe. This does not indicate the severity of harm for a piece of content.
      /// </summary>
      public enum HarmProbability {
        /// <summary>
        /// Probability is unspecified.
        /// </summary>
        [pbr::OriginalName("HARM_PROBABILITY_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// Content has a negligible chance of being unsafe.
        /// </summary>
        [pbr::OriginalName("NEGLIGIBLE")] Negligible = 1,
        /// <summary>
        /// Content has a low chance of being unsafe.
        /// </summary>
        [pbr::OriginalName("LOW")] Low = 2,
        /// <summary>
        /// Content has a medium chance of being unsafe.
        /// </summary>
        [pbr::OriginalName("MEDIUM")] Medium = 3,
        /// <summary>
        /// Content has a high chance of being unsafe.
        /// </summary>
        [pbr::OriginalName("HIGH")] High = 4,
      }

    }
    #endregion

  }

  /// <summary>
  /// Safety setting, affecting the safety-blocking behavior.
  ///
  /// Passing a safety setting for a category changes the allowed proability that
  /// content is blocked.
  /// </summary>
  public sealed partial class SafetySetting : pb::IMessage<SafetySetting>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SafetySetting> _parser = new pb::MessageParser<SafetySetting>(() => new SafetySetting());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SafetySetting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.SafetyReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetySetting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetySetting(SafetySetting other) : this() {
      category_ = other.category_;
      threshold_ = other.threshold_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SafetySetting Clone() {
      return new SafetySetting(this);
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 3;
    private global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory category_ = global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified;
    /// <summary>
    /// Required. The category for this setting.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    /// <summary>Field number for the "threshold" field.</summary>
    public const int ThresholdFieldNumber = 4;
    private global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold threshold_ = global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold.Unspecified;
    /// <summary>
    /// Required. Controls the probability threshold at which harm is blocked.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold Threshold {
      get { return threshold_; }
      set {
        threshold_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SafetySetting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SafetySetting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Category != other.Category) return false;
      if (Threshold != other.Threshold) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) hash ^= Category.GetHashCode();
      if (Threshold != global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold.Unspecified) hash ^= Threshold.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Category);
      }
      if (Threshold != global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Threshold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Category);
      }
      if (Threshold != global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Threshold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      if (Threshold != global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Threshold);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SafetySetting other) {
      if (other == null) {
        return;
      }
      if (other.Category != global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory.Unspecified) {
        Category = other.Category;
      }
      if (other.Threshold != global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold.Unspecified) {
        Threshold = other.Threshold;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            Category = (global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory) input.ReadEnum();
            break;
          }
          case 32: {
            Threshold = (global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            Category = (global::Google.Ai.Generativelanguage.V1Beta2.HarmCategory) input.ReadEnum();
            break;
          }
          case 32: {
            Threshold = (global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Types.HarmBlockThreshold) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SafetySetting message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Block at and beyond a specified harm probability.
      /// </summary>
      public enum HarmBlockThreshold {
        /// <summary>
        /// Threshold is unspecified.
        /// </summary>
        [pbr::OriginalName("HARM_BLOCK_THRESHOLD_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// Content with NEGLIGIBLE will be allowed.
        /// </summary>
        [pbr::OriginalName("BLOCK_LOW_AND_ABOVE")] BlockLowAndAbove = 1,
        /// <summary>
        /// Content with NEGLIGIBLE and LOW will be allowed.
        /// </summary>
        [pbr::OriginalName("BLOCK_MEDIUM_AND_ABOVE")] BlockMediumAndAbove = 2,
        /// <summary>
        /// Content with NEGLIGIBLE, LOW, and MEDIUM will be allowed.
        /// </summary>
        [pbr::OriginalName("BLOCK_ONLY_HIGH")] BlockOnlyHigh = 3,
        /// <summary>
        /// All content will be allowed.
        /// </summary>
        [pbr::OriginalName("BLOCK_NONE")] BlockNone = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
