// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ai/generativelanguage/v1beta2/text_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Ai.Generativelanguage.V1Beta2 {

  /// <summary>Holder for reflection information generated from google/ai/generativelanguage/v1beta2/text_service.proto</summary>
  public static partial class TextServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for google/ai/generativelanguage/v1beta2/text_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TextServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjdnb29nbGUvYWkvZ2VuZXJhdGl2ZWxhbmd1YWdlL3YxYmV0YTIvdGV4dF9z",
            "ZXJ2aWNlLnByb3RvEiRnb29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYx",
            "YmV0YTIaM2dvb2dsZS9haS9nZW5lcmF0aXZlbGFuZ3VhZ2UvdjFiZXRhMi9j",
            "aXRhdGlvbi5wcm90bxoxZ29vZ2xlL2FpL2dlbmVyYXRpdmVsYW5ndWFnZS92",
            "MWJldGEyL3NhZmV0eS5wcm90bxocZ29vZ2xlL2FwaS9hbm5vdGF0aW9ucy5w",
            "cm90bxoXZ29vZ2xlL2FwaS9jbGllbnQucHJvdG8aH2dvb2dsZS9hcGkvZmll",
            "bGRfYmVoYXZpb3IucHJvdG8aGWdvb2dsZS9hcGkvcmVzb3VyY2UucHJvdG8i",
            "0AMKE0dlbmVyYXRlVGV4dFJlcXVlc3QSPgoFbW9kZWwYASABKAlCL+BBAvpB",
            "KQonZ2VuZXJhdGl2ZWxhbmd1YWdlLmdvb2dsZWFwaXMuY29tL01vZGVsEkUK",
            "BnByb21wdBgCIAEoCzIwLmdvb2dsZS5haS5nZW5lcmF0aXZlbGFuZ3VhZ2Uu",
            "djFiZXRhMi5UZXh0UHJvbXB0QgPgQQISGAoLdGVtcGVyYXR1cmUYAyABKAJI",
            "AIgBARIcCg9jYW5kaWRhdGVfY291bnQYBCABKAVIAYgBARIeChFtYXhfb3V0",
            "cHV0X3Rva2VucxgFIAEoBUgCiAEBEhIKBXRvcF9wGAYgASgCSAOIAQESEgoF",
            "dG9wX2sYByABKAVIBIgBARJMCg9zYWZldHlfc2V0dGluZ3MYCCADKAsyMy5n",
            "b29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuU2FmZXR5U2V0",
            "dGluZxIWCg5zdG9wX3NlcXVlbmNlcxgJIAMoCUIOCgxfdGVtcGVyYXR1cmVC",
            "EgoQX2NhbmRpZGF0ZV9jb3VudEIUChJfbWF4X291dHB1dF90b2tlbnNCCAoG",
            "X3RvcF9wQggKBl90b3BfayL1AQoUR2VuZXJhdGVUZXh0UmVzcG9uc2USSAoK",
            "Y2FuZGlkYXRlcxgBIAMoCzI0Lmdvb2dsZS5haS5nZW5lcmF0aXZlbGFuZ3Vh",
            "Z2UudjFiZXRhMi5UZXh0Q29tcGxldGlvbhJECgdmaWx0ZXJzGAMgAygLMjMu",
            "Z29vZ2xlLmFpLmdlbmVyYXRpdmVsYW5ndWFnZS52MWJldGEyLkNvbnRlbnRG",
            "aWx0ZXISTQoPc2FmZXR5X2ZlZWRiYWNrGAQgAygLMjQuZ29vZ2xlLmFpLmdl",
            "bmVyYXRpdmVsYW5ndWFnZS52MWJldGEyLlNhZmV0eUZlZWRiYWNrIh8KClRl",
            "eHRQcm9tcHQSEQoEdGV4dBgBIAEoCUID4EECIuQBCg5UZXh0Q29tcGxldGlv",
            "bhITCgZvdXRwdXQYASABKAlCA+BBAxJKCg5zYWZldHlfcmF0aW5ncxgCIAMo",
            "CzIyLmdvb2dsZS5haS5nZW5lcmF0aXZlbGFuZ3VhZ2UudjFiZXRhMi5TYWZl",
            "dHlSYXRpbmcSWwoRY2l0YXRpb25fbWV0YWRhdGEYAyABKAsyNi5nb29nbGUu",
            "YWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuQ2l0YXRpb25NZXRhZGF0",
            "YUID4EEDSACIAQFCFAoSX2NpdGF0aW9uX21ldGFkYXRhImUKEEVtYmVkVGV4",
            "dFJlcXVlc3QSPgoFbW9kZWwYASABKAlCL+BBAvpBKQonZ2VuZXJhdGl2ZWxh",
            "bmd1YWdlLmdvb2dsZWFwaXMuY29tL01vZGVsEhEKBHRleHQYAiABKAlCA+BB",
            "AiJvChFFbWJlZFRleHRSZXNwb25zZRJMCgllbWJlZGRpbmcYASABKAsyLy5n",
            "b29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuRW1iZWRkaW5n",
            "QgPgQQNIAIgBAUIMCgpfZW1iZWRkaW5nIhoKCUVtYmVkZGluZxINCgV2YWx1",
            "ZRgBIAMoAjLzAwoLVGV4dFNlcnZpY2USgQIKDEdlbmVyYXRlVGV4dBI5Lmdv",
            "b2dsZS5haS5nZW5lcmF0aXZlbGFuZ3VhZ2UudjFiZXRhMi5HZW5lcmF0ZVRl",
            "eHRSZXF1ZXN0GjouZ29vZ2xlLmFpLmdlbmVyYXRpdmVsYW5ndWFnZS52MWJl",
            "dGEyLkdlbmVyYXRlVGV4dFJlc3BvbnNlInqC0+STAisiJi92MWJldGEyL3tt",
            "b2RlbD1tb2RlbHMvKn06Z2VuZXJhdGVUZXh0OgEq2kFGbW9kZWwscHJvbXB0",
            "LHRlbXBlcmF0dXJlLGNhbmRpZGF0ZV9jb3VudCxtYXhfb3V0cHV0X3Rva2Vu",
            "cyx0b3BfcCx0b3BfaxK5AQoJRW1iZWRUZXh0EjYuZ29vZ2xlLmFpLmdlbmVy",
            "YXRpdmVsYW5ndWFnZS52MWJldGEyLkVtYmVkVGV4dFJlcXVlc3QaNy5nb29n",
            "bGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTIuRW1iZWRUZXh0UmVz",
            "cG9uc2UiO4LT5JMCKCIjL3YxYmV0YTIve21vZGVsPW1vZGVscy8qfTplbWJl",
            "ZFRleHQ6ASraQQptb2RlbCx0ZXh0GiTKQSFnZW5lcmF0aXZlbGFuZ3VhZ2Uu",
            "Z29vZ2xlYXBpcy5jb21ClgEKKGNvbS5nb29nbGUuYWkuZ2VuZXJhdGl2ZWxh",
            "bmd1YWdlLnYxYmV0YTJCEFRleHRTZXJ2aWNlUHJvdG9QAVpWZ29vZ2xlLmdv",
            "bGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy9haS9nZW5lcmF0aXZlbGFu",
            "Z3VhZ2UvdjFiZXRhMjtnZW5lcmF0aXZlbGFuZ3VhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Ai.Generativelanguage.V1Beta2.CitationReflection.Descriptor, global::Google.Ai.Generativelanguage.V1Beta2.SafetyReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Api.ClientReflection.Descriptor, global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.GenerateTextRequest), global::Google.Ai.Generativelanguage.V1Beta2.GenerateTextRequest.Parser, new[]{ "Model", "Prompt", "Temperature", "CandidateCount", "MaxOutputTokens", "TopP", "TopK", "SafetySettings", "StopSequences" }, new[]{ "Temperature", "CandidateCount", "MaxOutputTokens", "TopP", "TopK" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.GenerateTextResponse), global::Google.Ai.Generativelanguage.V1Beta2.GenerateTextResponse.Parser, new[]{ "Candidates", "Filters", "SafetyFeedback" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.TextPrompt), global::Google.Ai.Generativelanguage.V1Beta2.TextPrompt.Parser, new[]{ "Text" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.TextCompletion), global::Google.Ai.Generativelanguage.V1Beta2.TextCompletion.Parser, new[]{ "Output", "SafetyRatings", "CitationMetadata" }, new[]{ "CitationMetadata" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.EmbedTextRequest), global::Google.Ai.Generativelanguage.V1Beta2.EmbedTextRequest.Parser, new[]{ "Model", "Text" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.EmbedTextResponse), global::Google.Ai.Generativelanguage.V1Beta2.EmbedTextResponse.Parser, new[]{ "Embedding" }, new[]{ "Embedding" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta2.Embedding), global::Google.Ai.Generativelanguage.V1Beta2.Embedding.Parser, new[]{ "Value" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Request to generate a text completion response from the model.
  /// </summary>
  public sealed partial class GenerateTextRequest : pb::IMessage<GenerateTextRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateTextRequest> _parser = new pb::MessageParser<GenerateTextRequest>(() => new GenerateTextRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateTextRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.TextServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateTextRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateTextRequest(GenerateTextRequest other) : this() {
      _hasBits0 = other._hasBits0;
      model_ = other.model_;
      prompt_ = other.prompt_ != null ? other.prompt_.Clone() : null;
      temperature_ = other.temperature_;
      candidateCount_ = other.candidateCount_;
      maxOutputTokens_ = other.maxOutputTokens_;
      topP_ = other.topP_;
      topK_ = other.topK_;
      safetySettings_ = other.safetySettings_.Clone();
      stopSequences_ = other.stopSequences_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateTextRequest Clone() {
      return new GenerateTextRequest(this);
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 1;
    private string model_ = "";
    /// <summary>
    /// Required. The model name to use with the format name=models/{model}.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prompt" field.</summary>
    public const int PromptFieldNumber = 2;
    private global::Google.Ai.Generativelanguage.V1Beta2.TextPrompt prompt_;
    /// <summary>
    /// Required. The free-form input text given to the model as a prompt.
    ///
    /// Given a prompt, the model will generate a TextCompletion response it
    /// predicts as the completion of the input text.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.TextPrompt Prompt {
      get { return prompt_; }
      set {
        prompt_ = value;
      }
    }

    /// <summary>Field number for the "temperature" field.</summary>
    public const int TemperatureFieldNumber = 3;
    private float temperature_;
    /// <summary>
    /// Controls the randomness of the output.
    /// Note: The default value varies by model, see the `Model.temperature`
    /// attribute of the `Model` returned the `getModel` function.
    ///
    /// Values can range from [0.0,1.0],
    /// inclusive. A value closer to 1.0 will produce responses that are more
    /// varied and creative, while a value closer to 0.0 will typically result in
    /// more straightforward responses from the model.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Temperature {
      get { if ((_hasBits0 & 1) != 0) { return temperature_; } else { return 0F; } }
      set {
        _hasBits0 |= 1;
        temperature_ = value;
      }
    }
    /// <summary>Gets whether the "temperature" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTemperature {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "temperature" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTemperature() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "candidate_count" field.</summary>
    public const int CandidateCountFieldNumber = 4;
    private int candidateCount_;
    /// <summary>
    /// Number of generated responses to return.
    ///
    /// This value must be between [1, 8], inclusive. If unset, this will default
    /// to 1.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CandidateCount {
      get { if ((_hasBits0 & 2) != 0) { return candidateCount_; } else { return 0; } }
      set {
        _hasBits0 |= 2;
        candidateCount_ = value;
      }
    }
    /// <summary>Gets whether the "candidate_count" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCandidateCount {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "candidate_count" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCandidateCount() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "max_output_tokens" field.</summary>
    public const int MaxOutputTokensFieldNumber = 5;
    private int maxOutputTokens_;
    /// <summary>
    /// The maximum number of tokens to include in a candidate.
    ///
    /// If unset, this will default to 64.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxOutputTokens {
      get { if ((_hasBits0 & 4) != 0) { return maxOutputTokens_; } else { return 0; } }
      set {
        _hasBits0 |= 4;
        maxOutputTokens_ = value;
      }
    }
    /// <summary>Gets whether the "max_output_tokens" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMaxOutputTokens {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "max_output_tokens" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMaxOutputTokens() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "top_p" field.</summary>
    public const int TopPFieldNumber = 6;
    private float topP_;
    /// <summary>
    /// The maximum cumulative probability of tokens to consider when sampling.
    ///
    /// The model uses combined Top-k and nucleus sampling.
    ///
    /// Tokens are sorted based on their assigned probabilities so that only the
    /// most liekly tokens are considered. Top-k sampling directly limits the
    /// maximum number of tokens to consider, while Nucleus sampling limits number
    /// of tokens based on the cumulative probability.
    ///
    /// Note: The default value varies by model, see the `Model.top_p`
    /// attribute of the `Model` returned the `getModel` function.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TopP {
      get { if ((_hasBits0 & 8) != 0) { return topP_; } else { return 0F; } }
      set {
        _hasBits0 |= 8;
        topP_ = value;
      }
    }
    /// <summary>Gets whether the "top_p" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTopP {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "top_p" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTopP() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "top_k" field.</summary>
    public const int TopKFieldNumber = 7;
    private int topK_;
    /// <summary>
    /// The maximum number of tokens to consider when sampling.
    ///
    /// The model uses combined Top-k and nucleus sampling.
    ///
    /// Top-k sampling considers the set of `top_k` most probable tokens.
    /// Defaults to 40.
    ///
    /// Note: The default value varies by model, see the `Model.top_k`
    /// attribute of the `Model` returned the `getModel` function.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TopK {
      get { if ((_hasBits0 & 16) != 0) { return topK_; } else { return 0; } }
      set {
        _hasBits0 |= 16;
        topK_ = value;
      }
    }
    /// <summary>Gets whether the "top_k" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTopK {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "top_k" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTopK() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "safety_settings" field.</summary>
    public const int SafetySettingsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting> _repeated_safetySettings_codec
        = pb::FieldCodec.ForMessage(66, global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting> safetySettings_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting>();
    /// <summary>
    /// A list of unique `SafetySetting` instances for blocking unsafe content.
    ///
    /// that will be enforced on the `GenerateTextRequest.prompt` and
    /// `GenerateTextResponse.candidates`. There should not be more than one
    /// setting for each `SafetyCategory` type. The API will block any prompts and
    /// responses that fail to meet the thresholds set by these settings. This list
    /// overrides the default settings for each `SafetyCategory` specified in the
    /// safety_settings. If there is no `SafetySetting` for a given
    /// `SafetyCategory` provided in the list, the API will use the default safety
    /// setting for that category.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetySetting> SafetySettings {
      get { return safetySettings_; }
    }

    /// <summary>Field number for the "stop_sequences" field.</summary>
    public const int StopSequencesFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_stopSequences_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> stopSequences_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// The set of character sequences (up to 5) that will stop output generation.
    /// If specified, the API will stop at the first appearance of a stop
    /// sequence. The stop sequence will not be included as part of the response.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> StopSequences {
      get { return stopSequences_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateTextRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateTextRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Model != other.Model) return false;
      if (!object.Equals(Prompt, other.Prompt)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Temperature, other.Temperature)) return false;
      if (CandidateCount != other.CandidateCount) return false;
      if (MaxOutputTokens != other.MaxOutputTokens) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TopP, other.TopP)) return false;
      if (TopK != other.TopK) return false;
      if(!safetySettings_.Equals(other.safetySettings_)) return false;
      if(!stopSequences_.Equals(other.stopSequences_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      if (prompt_ != null) hash ^= Prompt.GetHashCode();
      if (HasTemperature) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Temperature);
      if (HasCandidateCount) hash ^= CandidateCount.GetHashCode();
      if (HasMaxOutputTokens) hash ^= MaxOutputTokens.GetHashCode();
      if (HasTopP) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TopP);
      if (HasTopK) hash ^= TopK.GetHashCode();
      hash ^= safetySettings_.GetHashCode();
      hash ^= stopSequences_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Model.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Model);
      }
      if (prompt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Prompt);
      }
      if (HasTemperature) {
        output.WriteRawTag(29);
        output.WriteFloat(Temperature);
      }
      if (HasCandidateCount) {
        output.WriteRawTag(32);
        output.WriteInt32(CandidateCount);
      }
      if (HasMaxOutputTokens) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxOutputTokens);
      }
      if (HasTopP) {
        output.WriteRawTag(53);
        output.WriteFloat(TopP);
      }
      if (HasTopK) {
        output.WriteRawTag(56);
        output.WriteInt32(TopK);
      }
      safetySettings_.WriteTo(output, _repeated_safetySettings_codec);
      stopSequences_.WriteTo(output, _repeated_stopSequences_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Model.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Model);
      }
      if (prompt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Prompt);
      }
      if (HasTemperature) {
        output.WriteRawTag(29);
        output.WriteFloat(Temperature);
      }
      if (HasCandidateCount) {
        output.WriteRawTag(32);
        output.WriteInt32(CandidateCount);
      }
      if (HasMaxOutputTokens) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxOutputTokens);
      }
      if (HasTopP) {
        output.WriteRawTag(53);
        output.WriteFloat(TopP);
      }
      if (HasTopK) {
        output.WriteRawTag(56);
        output.WriteInt32(TopK);
      }
      safetySettings_.WriteTo(ref output, _repeated_safetySettings_codec);
      stopSequences_.WriteTo(ref output, _repeated_stopSequences_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      if (prompt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Prompt);
      }
      if (HasTemperature) {
        size += 1 + 4;
      }
      if (HasCandidateCount) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CandidateCount);
      }
      if (HasMaxOutputTokens) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxOutputTokens);
      }
      if (HasTopP) {
        size += 1 + 4;
      }
      if (HasTopK) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopK);
      }
      size += safetySettings_.CalculateSize(_repeated_safetySettings_codec);
      size += stopSequences_.CalculateSize(_repeated_stopSequences_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateTextRequest other) {
      if (other == null) {
        return;
      }
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      if (other.prompt_ != null) {
        if (prompt_ == null) {
          Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.TextPrompt();
        }
        Prompt.MergeFrom(other.Prompt);
      }
      if (other.HasTemperature) {
        Temperature = other.Temperature;
      }
      if (other.HasCandidateCount) {
        CandidateCount = other.CandidateCount;
      }
      if (other.HasMaxOutputTokens) {
        MaxOutputTokens = other.MaxOutputTokens;
      }
      if (other.HasTopP) {
        TopP = other.TopP;
      }
      if (other.HasTopK) {
        TopK = other.TopK;
      }
      safetySettings_.Add(other.safetySettings_);
      stopSequences_.Add(other.stopSequences_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Model = input.ReadString();
            break;
          }
          case 18: {
            if (prompt_ == null) {
              Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.TextPrompt();
            }
            input.ReadMessage(Prompt);
            break;
          }
          case 29: {
            Temperature = input.ReadFloat();
            break;
          }
          case 32: {
            CandidateCount = input.ReadInt32();
            break;
          }
          case 40: {
            MaxOutputTokens = input.ReadInt32();
            break;
          }
          case 53: {
            TopP = input.ReadFloat();
            break;
          }
          case 56: {
            TopK = input.ReadInt32();
            break;
          }
          case 66: {
            safetySettings_.AddEntriesFrom(input, _repeated_safetySettings_codec);
            break;
          }
          case 74: {
            stopSequences_.AddEntriesFrom(input, _repeated_stopSequences_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Model = input.ReadString();
            break;
          }
          case 18: {
            if (prompt_ == null) {
              Prompt = new global::Google.Ai.Generativelanguage.V1Beta2.TextPrompt();
            }
            input.ReadMessage(Prompt);
            break;
          }
          case 29: {
            Temperature = input.ReadFloat();
            break;
          }
          case 32: {
            CandidateCount = input.ReadInt32();
            break;
          }
          case 40: {
            MaxOutputTokens = input.ReadInt32();
            break;
          }
          case 53: {
            TopP = input.ReadFloat();
            break;
          }
          case 56: {
            TopK = input.ReadInt32();
            break;
          }
          case 66: {
            safetySettings_.AddEntriesFrom(ref input, _repeated_safetySettings_codec);
            break;
          }
          case 74: {
            stopSequences_.AddEntriesFrom(ref input, _repeated_stopSequences_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response from the model, including candidate completions.
  /// </summary>
  public sealed partial class GenerateTextResponse : pb::IMessage<GenerateTextResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateTextResponse> _parser = new pb::MessageParser<GenerateTextResponse>(() => new GenerateTextResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateTextResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.TextServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateTextResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateTextResponse(GenerateTextResponse other) : this() {
      candidates_ = other.candidates_.Clone();
      filters_ = other.filters_.Clone();
      safetyFeedback_ = other.safetyFeedback_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateTextResponse Clone() {
      return new GenerateTextResponse(this);
    }

    /// <summary>Field number for the "candidates" field.</summary>
    public const int CandidatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.TextCompletion> _repeated_candidates_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Ai.Generativelanguage.V1Beta2.TextCompletion.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.TextCompletion> candidates_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.TextCompletion>();
    /// <summary>
    /// Candidate responses from the model.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.TextCompletion> Candidates {
      get { return candidates_; }
    }

    /// <summary>Field number for the "filters" field.</summary>
    public const int FiltersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter> _repeated_filters_codec
        = pb::FieldCodec.ForMessage(26, global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter> filters_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter>();
    /// <summary>
    /// A set of content filtering metadata for the prompt and response
    /// text.
    ///
    /// This indicates which `SafetyCategory`(s) blocked a
    /// candidate from this response, the lowest `HarmProbability`
    /// that triggered a block, and the HarmThreshold setting for that category.
    /// This indicates the smallest change to the `SafetySettings` that would be
    /// necessary to unblock at least 1 response.
    ///
    /// The blocking is configured by the `SafetySettings` in the request (or the
    /// default `SafetySettings` of the API).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.ContentFilter> Filters {
      get { return filters_; }
    }

    /// <summary>Field number for the "safety_feedback" field.</summary>
    public const int SafetyFeedbackFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.SafetyFeedback> _repeated_safetyFeedback_codec
        = pb::FieldCodec.ForMessage(34, global::Google.Ai.Generativelanguage.V1Beta2.SafetyFeedback.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetyFeedback> safetyFeedback_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetyFeedback>();
    /// <summary>
    /// Returns any safety feedback related to content filtering.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetyFeedback> SafetyFeedback {
      get { return safetyFeedback_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateTextResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateTextResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!candidates_.Equals(other.candidates_)) return false;
      if(!filters_.Equals(other.filters_)) return false;
      if(!safetyFeedback_.Equals(other.safetyFeedback_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= candidates_.GetHashCode();
      hash ^= filters_.GetHashCode();
      hash ^= safetyFeedback_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      candidates_.WriteTo(output, _repeated_candidates_codec);
      filters_.WriteTo(output, _repeated_filters_codec);
      safetyFeedback_.WriteTo(output, _repeated_safetyFeedback_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      candidates_.WriteTo(ref output, _repeated_candidates_codec);
      filters_.WriteTo(ref output, _repeated_filters_codec);
      safetyFeedback_.WriteTo(ref output, _repeated_safetyFeedback_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += candidates_.CalculateSize(_repeated_candidates_codec);
      size += filters_.CalculateSize(_repeated_filters_codec);
      size += safetyFeedback_.CalculateSize(_repeated_safetyFeedback_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateTextResponse other) {
      if (other == null) {
        return;
      }
      candidates_.Add(other.candidates_);
      filters_.Add(other.filters_);
      safetyFeedback_.Add(other.safetyFeedback_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            candidates_.AddEntriesFrom(input, _repeated_candidates_codec);
            break;
          }
          case 26: {
            filters_.AddEntriesFrom(input, _repeated_filters_codec);
            break;
          }
          case 34: {
            safetyFeedback_.AddEntriesFrom(input, _repeated_safetyFeedback_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            candidates_.AddEntriesFrom(ref input, _repeated_candidates_codec);
            break;
          }
          case 26: {
            filters_.AddEntriesFrom(ref input, _repeated_filters_codec);
            break;
          }
          case 34: {
            safetyFeedback_.AddEntriesFrom(ref input, _repeated_safetyFeedback_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Text given to the model as a prompt.
  ///
  /// The Model will use this TextPrompt to Generate a text completion.
  /// </summary>
  public sealed partial class TextPrompt : pb::IMessage<TextPrompt>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextPrompt> _parser = new pb::MessageParser<TextPrompt>(() => new TextPrompt());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextPrompt> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.TextServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextPrompt() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextPrompt(TextPrompt other) : this() {
      text_ = other.text_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextPrompt Clone() {
      return new TextPrompt(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    /// <summary>
    /// Required. The prompt text.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextPrompt);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextPrompt other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextPrompt other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Output text returned from a model.
  /// </summary>
  public sealed partial class TextCompletion : pb::IMessage<TextCompletion>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextCompletion> _parser = new pb::MessageParser<TextCompletion>(() => new TextCompletion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextCompletion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.TextServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextCompletion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextCompletion(TextCompletion other) : this() {
      output_ = other.output_;
      safetyRatings_ = other.safetyRatings_.Clone();
      citationMetadata_ = other.citationMetadata_ != null ? other.citationMetadata_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextCompletion Clone() {
      return new TextCompletion(this);
    }

    /// <summary>Field number for the "output" field.</summary>
    public const int OutputFieldNumber = 1;
    private string output_ = "";
    /// <summary>
    /// Output only. The generated text returned from the model.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Output {
      get { return output_; }
      set {
        output_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "safety_ratings" field.</summary>
    public const int SafetyRatingsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating> _repeated_safetyRatings_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating.Parser);
    private readonly pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating> safetyRatings_ = new pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating>();
    /// <summary>
    /// Ratings for the safety of a response.
    ///
    /// There is at most one rating per category.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ai.Generativelanguage.V1Beta2.SafetyRating> SafetyRatings {
      get { return safetyRatings_; }
    }

    /// <summary>Field number for the "citation_metadata" field.</summary>
    public const int CitationMetadataFieldNumber = 3;
    private global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata citationMetadata_;
    /// <summary>
    /// Output only. Citation information for model-generated `output` in this
    /// `TextCompletion`.
    ///
    /// This field may be populated with attribution information for any text
    /// included in the `output`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata CitationMetadata {
      get { return citationMetadata_; }
      set {
        citationMetadata_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextCompletion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextCompletion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Output != other.Output) return false;
      if(!safetyRatings_.Equals(other.safetyRatings_)) return false;
      if (!object.Equals(CitationMetadata, other.CitationMetadata)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Output.Length != 0) hash ^= Output.GetHashCode();
      hash ^= safetyRatings_.GetHashCode();
      if (citationMetadata_ != null) hash ^= CitationMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Output.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Output);
      }
      safetyRatings_.WriteTo(output, _repeated_safetyRatings_codec);
      if (citationMetadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CitationMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Output.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Output);
      }
      safetyRatings_.WriteTo(ref output, _repeated_safetyRatings_codec);
      if (citationMetadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CitationMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Output.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Output);
      }
      size += safetyRatings_.CalculateSize(_repeated_safetyRatings_codec);
      if (citationMetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CitationMetadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextCompletion other) {
      if (other == null) {
        return;
      }
      if (other.Output.Length != 0) {
        Output = other.Output;
      }
      safetyRatings_.Add(other.safetyRatings_);
      if (other.citationMetadata_ != null) {
        if (citationMetadata_ == null) {
          CitationMetadata = new global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata();
        }
        CitationMetadata.MergeFrom(other.CitationMetadata);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Output = input.ReadString();
            break;
          }
          case 18: {
            safetyRatings_.AddEntriesFrom(input, _repeated_safetyRatings_codec);
            break;
          }
          case 26: {
            if (citationMetadata_ == null) {
              CitationMetadata = new global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata();
            }
            input.ReadMessage(CitationMetadata);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Output = input.ReadString();
            break;
          }
          case 18: {
            safetyRatings_.AddEntriesFrom(ref input, _repeated_safetyRatings_codec);
            break;
          }
          case 26: {
            if (citationMetadata_ == null) {
              CitationMetadata = new global::Google.Ai.Generativelanguage.V1Beta2.CitationMetadata();
            }
            input.ReadMessage(CitationMetadata);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request to get a text embedding from the model.
  /// </summary>
  public sealed partial class EmbedTextRequest : pb::IMessage<EmbedTextRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EmbedTextRequest> _parser = new pb::MessageParser<EmbedTextRequest>(() => new EmbedTextRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EmbedTextRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.TextServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbedTextRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbedTextRequest(EmbedTextRequest other) : this() {
      model_ = other.model_;
      text_ = other.text_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbedTextRequest Clone() {
      return new EmbedTextRequest(this);
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 1;
    private string model_ = "";
    /// <summary>
    /// Required. The model name to use with the format model=models/{model}.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 2;
    private string text_ = "";
    /// <summary>
    /// Required. The free-form input text that the model will turn into an
    /// embedding.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EmbedTextRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EmbedTextRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Model != other.Model) return false;
      if (Text != other.Text) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Model.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Model);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Model.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Model);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EmbedTextRequest other) {
      if (other == null) {
        return;
      }
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Model = input.ReadString();
            break;
          }
          case 18: {
            Text = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Model = input.ReadString();
            break;
          }
          case 18: {
            Text = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response to a EmbedTextRequest.
  /// </summary>
  public sealed partial class EmbedTextResponse : pb::IMessage<EmbedTextResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EmbedTextResponse> _parser = new pb::MessageParser<EmbedTextResponse>(() => new EmbedTextResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EmbedTextResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.TextServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbedTextResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbedTextResponse(EmbedTextResponse other) : this() {
      embedding_ = other.embedding_ != null ? other.embedding_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbedTextResponse Clone() {
      return new EmbedTextResponse(this);
    }

    /// <summary>Field number for the "embedding" field.</summary>
    public const int EmbeddingFieldNumber = 1;
    private global::Google.Ai.Generativelanguage.V1Beta2.Embedding embedding_;
    /// <summary>
    /// Output only. The embedding generated from the input text.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta2.Embedding Embedding {
      get { return embedding_; }
      set {
        embedding_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EmbedTextResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EmbedTextResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Embedding, other.Embedding)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (embedding_ != null) hash ^= Embedding.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (embedding_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Embedding);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (embedding_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Embedding);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (embedding_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Embedding);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EmbedTextResponse other) {
      if (other == null) {
        return;
      }
      if (other.embedding_ != null) {
        if (embedding_ == null) {
          Embedding = new global::Google.Ai.Generativelanguage.V1Beta2.Embedding();
        }
        Embedding.MergeFrom(other.Embedding);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (embedding_ == null) {
              Embedding = new global::Google.Ai.Generativelanguage.V1Beta2.Embedding();
            }
            input.ReadMessage(Embedding);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (embedding_ == null) {
              Embedding = new global::Google.Ai.Generativelanguage.V1Beta2.Embedding();
            }
            input.ReadMessage(Embedding);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// A list of floats representing the embedding.
  /// </summary>
  public sealed partial class Embedding : pb::IMessage<Embedding>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Embedding> _parser = new pb::MessageParser<Embedding>(() => new Embedding());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Embedding> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta2.TextServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Embedding() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Embedding(Embedding other) : this() {
      value_ = other.value_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Embedding Clone() {
      return new Embedding(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_value_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> value_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// The embedding values.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Value {
      get { return value_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Embedding);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Embedding other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!value_.Equals(other.value_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= value_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      value_.WriteTo(output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      value_.WriteTo(ref output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += value_.CalculateSize(_repeated_value_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Embedding other) {
      if (other == null) {
        return;
      }
      value_.Add(other.value_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            value_.AddEntriesFrom(input, _repeated_value_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            value_.AddEntriesFrom(ref input, _repeated_value_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
